### ISSUE TITLE
Add currency estimations in chaos/exalts

### ISSUE THREAD

**Issue by HenriqueA43** [rfcoding/PathOfCrafting#2]
If feasible make a pull from poeninja for conversion prices and display at the bottom of currency spendings as an estimation for current market value spent (e.g. spent 550 alts 10c and 2ex -> total spendings: 390c/3exa )
I am willing to work on this since I also code.

**Comment by rfcoding** [comment]
Hi, thank you for reaching out!
This is a great suggestion and something we have actually started looking
into already.
The app is sadly not ready to be open source but maybe in the future.

**Comment by rfcoding** [comment]
This was added in 1.2
