### ISSUE TITLE
Beastcrafting with 'cannot roll attack mods' works incorrectly

### ISSUE THREAD

**Issue by master2080** [rfcoding/PathOfCrafting#4]
I tried beastcrafting "Add a prefix, remove a random suffix" on an item with "cannot roll attack mods" and a prefix and my result contained a prefix which was an attack mod.

Hopefully this is a simple fix of just swapping the order of operations.

**Comment by rfcoding** [comment]
Hi, thank you for reaching out!

We are aware of this issue and will look into it for next release.
