### ISSUE TITLE
Error when trying to load a saved item

### ISSUE THREAD

**Issue by chancesk123** [rfcoding/PathOfCrafting#5]
Here is a picture of it.
![Screenshot_20190822-193332](https://user-images.githubusercontent.com/54422257/63556719-e2b3de80-c513-11e9-8735-8c3bbdf680fd.png)
This is on the Android version

**Comment by rfcoding** [comment]
Hey, sorry about the inconvenience. This is a bug with backwards compatibility between this and the previous version. You can either clear the data for the app or re-install it for it to work again. Sadly, this will of course remove all your old items.

**Comment by rfcoding** [comment]
This is now fixed in 1.1.1 which is available on the play store.
