### ISSUE TITLE
Corrupting a saved item to gain a new implicit bug

### ISSUE THREAD

**Issue by desluOs** [rfcoding/PathOfCrafting#8]
I have a saved item that I corrupted to get a new implicit.  When I went back and didnt save changes to the item, then reloaded the same item, it was not corrupted but still had the new implicit.

Edit:  the only way to make the implicit return to normal is by returning to the main menu or restarting the app, then the implicit is normal.

**Comment by rfcoding** [comment]
This should be fixed in 1.3.1, please let us know otherwise.
